# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/libml',
                'doc_host': 'https://sagarkr666.github.io',
                'git_url': 'https://github.com/sagarkr666/libml',
                'lib_path': 'libml'},
  'syms': {'libml.core': {'libml.core.foo': ('core.html#foo', 'libml/core.py')}}}
